//公共的配置信息
module.exports={
    email:{
        server:'QQ',
        user:'3320407219@qq.com',
        pass:'qbjatflpssyrchje'
    },
    mysql:{
        host:'127.0.0.1',
        port:3306,
        user:'root',
        password:'root',
        database:'merchandise'
    }
}